server {
    listen 80;
    listen [::]:80;
    server_name mirror.safiabidi.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl ipv6only=on;
    server_name mirror.safiabidi.com;

    ssl_certificate /etc/letsencrypt/live/mirror.safiabidi.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mirror.safiabidi.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    root /srv/archmirror;
    autoindex on;
    access_log /var/log/nginx/archmirror.access.log;
    error_log /var/log/nginx/archmirror.error.log;

    location / {
        try_files $uri $uri/ =404;
    }

    location /stats.json {
        add_header Access-Control-Allow-Origin "https://safiabidi.com";
        add_header Cache-Control "no-store";
        try_files $uri =404;
    }

    location /dashboard {
        alias /srv/archmirror-dashboard;
        index index.html;
    }
}
