services:
  mirror-nginx:
    user: "0:0"
    build: ./nginx
    container_name: mirror-nginx
    restart: unless-stopped
    environment:
      - TZ=Africa/Tunis
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - mirror-data:/srv/archmirror:ro
      - mirror-dashboard:/srv/archmirror-dashboard:ro
      - nginx-logs:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - mirror-sync

  mirror-sync:
    user: "0:0"
    build: ./sync
    container_name: mirror-sync
    restart: unless-stopped
    volumes:
      - mirror-data:/srv/archmirror
    environment:
      - SYNC_HOUR=3
      - SYNC_MINUTE=17

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=90d'

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "127.0.0.1:9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    restart: unless-stopped
    ports:
      - "127.0.0.1:9113:9113"
    command:
      - '--nginx.scrape-uri=http://mirror-nginx:8080/stub_status'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "0.0.0.0:3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=changeme
      - GF_USERS_ALLOW_SIGN_UP=false

volumes:
  mirror-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/archmirror
  mirror-dashboard:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/archmirror-dashboard
  nginx-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/log/nginx
  prometheus-data:
  grafana-data:
